### ISSUE TITLE
bike shed update fails on macOS with "cannot import name viewkeys"

### ISSUE THREAD

**Issue by smfr** [speced/bikeshed#1136]
I cloned Bikeshed at b43bcf8d18510de03d8b56c5e878eea93e955427

sudo pip install  --editable seemed to work OK:

 7$ $ sudo pip install --editable ./bikeshed/
Password:
The directory '/Users/smfr/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/smfr/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining file:///Volumes/Data/Development/w3c/bikeshed
Collecting pygments (from Bikeshed==0.0.0)
  Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB)
    100% |████████████████████████████████| 849kB 1.4MB/s 
Collecting lxml (from Bikeshed==0.0.0)
  Downloading lxml-4.1.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (8.7MB)
    100% |████████████████████████████████| 8.7MB 159kB/s 
Requirement already satisfied: html5lib in /Users/smfr/Library/Python/2.7/lib/python/site-packages (from Bikeshed==0.0.0)
Collecting cssselect (from Bikeshed==0.0.0)
  Downloading cssselect-1.0.1-py2.py3-none-any.whl
Requirement already satisfied: webencodings in /Users/smfr/Library/Python/2.7/lib/python/site-packages (from html5lib->Bikeshed==0.0.0)
Requirement already satisfied: setuptools>=18.5 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from html5lib->Bikeshed==0.0.0)
Requirement already satisfied: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from html5lib->Bikeshed==0.0.0)
Installing collected packages: pygments, lxml, cssselect, Bikeshed
  Running setup.py develop for Bikeshed
Successfully installed Bikeshed cssselect-1.0.1 lxml-4.1.1 pygments-2.2.0

but bikeshed update fails:

 9$ $ bikeshed update
Traceback (most recent call last):
  File "/usr/local/bin/bikeshed", line 9, in <module>
    load_entry_point('Bikeshed==0.0.0', 'console_scripts', 'bikeshed')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Volumes/Data/Development/w3c/bikeshed/bikeshed/__init__.py", line 4, in <module>
    from .cli import main
  File "/Volumes/Data/Development/w3c/bikeshed/bikeshed/cli.py", line 9, in <module>
    from . import metadata
  File "/Volumes/Data/Development/w3c/bikeshed/bikeshed/metadata.py", line 16, in <module>
    from . import markdown
  File "/Volumes/Data/Development/w3c/bikeshed/bikeshed/markdown.py", line 5, in <module>
    from .htmlhelpers import escapeAttr
  File "/Volumes/Data/Development/w3c/bikeshed/bikeshed/htmlhelpers.py", line 4, in <module>
    import html5lib
  File "/Users/smfr/Library/Python/2.7/lib/python/site-packages/html5lib/__init__.py", line 16, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/Users/smfr/Library/Python/2.7/lib/python/site-packages/html5lib/html5parser.py", line 2, in <module>
    from six import with_metaclass, viewkeys, PY3
ImportError: cannot import name viewkeys

**Comment by smfr** [comment]
OS version is macOS High Sierra (build number 17A364).

**Comment by smfr** [comment]
six.py is __version__ = "1.10.0"

Maybe https://stackoverflow.com/questions/39658404/python-cannot-import-name-viewkeys

**Comment by smfr** [comment]
Fixed with `sudo pip install html5lib==1.0b8`

**Comment by tabatkins** [comment]
Closing as this was a bug in a dependancy that got fixed a long time ago.
