### ISSUE TITLE
API is returning Python errors

### ISSUE THREAD

**Issue by apasel422** [speced/bikeshed#2475]
https://api.csswg.org/bikeshed/

```
Error running preprocessor, returned code: 1.
Traceback (most recent call last):
  File "/sites/api.csswg.org/python310venv/bin/bikeshed", line 8, in 
    sys.exit(main())
  File "/sites/api.csswg.org/python310venv/lib/python3.10/site-packages/bikeshed/cli.py", line 430, in main
    handleSpec(options, extras)
  File "/sites/api.csswg.org/python310venv/lib/python3.10/site-packages/bikeshed/cli.py", line 475, in handleSpec
    doc = Spec(
  File "/sites/api.csswg.org/python310venv/lib/python3.10/site-packages/bikeshed/Spec.py", line 86, in __init__
    self.valid = self.initializeState()
  File "/sites/api.csswg.org/python310venv/lib/python3.10/site-packages/bikeshed/Spec.py", line 116, in initializeState
    self.extraStyles["style-colors"] = getModuleFile("Spec-colors.css")
  File "/sites/api.csswg.org/python310venv/lib/python3.10/site-packages/bikeshed/Spec.py", line 560, in getModuleFile
    with open(config.scriptPath(".", filename), "r", encoding="utf-8") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/sites/api.csswg.org/python310venv/lib/python3.10/site-packages/bikeshed/./Spec-colors.css'
```

**Comment by tabatkins** [comment]
Yup, fixed by 3.11.9, which appears to be installed on the server now.
