### ISSUE TITLE
New release? :)

### ISSUE THREAD

**Issue by nicolo-ribaudo** [speced/bikeshed#2980]
Hi, I just had to install bikeshed after cloning a new repo but it's failing on MacOS, because one of it's dependencies (pillow 10.2.0) cannot be installed:
```js
Collecting pillow==10.2.0 (from bikeshed)
  Using cached pillow-10.2.0.tar.gz (46.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/Users/nic/Documents/dev/github.com/tc39/ecma426/.venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Users/nic/Documents/dev/github.com/tc39/ecma426/.venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nic/Documents/dev/github.com/tc39/ecma426/.venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/bg/d5r9tspx5hn87zp52mcl82dh0000gn/T/pip-build-env-luro2yv0/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/bg/d5r9tspx5hn87zp52mcl82dh0000gn/T/pip-build-env-luro2yv0/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/bg/d5r9tspx5hn87zp52mcl82dh0000gn/T/pip-build-env-luro2yv0/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 31, in <module>
        File "<string>", line 28, in get_version
      KeyError: '__version__'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

pillow 11.0.0 seems to work, and I see that you are already using it on `main`. Releasing a new version of bikeshed with the updated requirements would fix the problem.

**EDIT:** As a workaround, I'm installing bikeshed from GitHub rather than from pypi

**Comment by tabatkins** [comment]
Ah yeah, no problem, happy to do a req-bump release. One sec.

**Comment by tabatkins** [comment]
And done, version 4.2.8 has all the new dep updates (I rolled in a handful more than dependabot was giving me).

**Comment by nicolo-ribaudo** [comment]
Thank you!
